### ISSUE TITLE
when I open xcode it seems that the project lost some files,how to fix it,thanks

### ISSUE THREAD

**Issue by coolzc** [kaorukobo/pdf2png-mac#1]

**Comment by kaorukobo** [comment]
What version of Xcode do you use?  I am not familier to recent XCode tools.
If you fail to build it with your XCode, try building with `make` program.

Thanks.

**Comment by coolzc** [comment]
My version of Xcode is 6.1.
I'm new to do with Mac OS coding.I think there is some big change due to the version of Xcode,still I can't build successfully.

**Comment by kaorukobo** [comment]
I have almost same version (6.1.1) of XCode on my Mac. However, for now, I cannot take time to learn of its usage and make changes to this code for supporting it.

Meanwhile, XCode comes with command-line build tools including gcc. So you should try `make` to compile this program. I confirmed the build using `make` get successful with my XCode 6.1.1.
