### ISSUE TITLE
Output path

### ISSUE THREAD

**Issue by RayPS** [kaorukobo/pdf2png-mac#2]
Hi kaorukobo, this project is amazing.
I'm trying to make an OS X application to generate mobile app assets from pdf.
I need a little help from you.
1. Can you add an option "--output" so we can set the output file name and path?
2. Can we don't append "xxx-p1" if "--page" is not defined?

Thank you!

**Comment by RayPS** [comment]
https://github.com/RayPS/P2AA

**Comment by kaorukobo** [comment]
Hi, RayPS. Thanks for your suggestion, now version ce093a6 supports --output option. Check it out.

Kaorukobo
